services:
  app:
    image: node:19-alpine
    command: sh -c "rm -rf ./node_modules && rm -rf ./dist && npm install && npx prisma db push && npm run build && npm run start:prod"
    restart: always
    ports:
      - 3000:3000
    working_dir: /app
    container_name: mind_control_app
    volumes:
      - ./:/app
  mysqlDB:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    container_name: mind_control_mysql
    environment:
      - MYSQL_DATABASE=MIND_CONTROL
      - MYSQL_CONTAINER_NAME=mysql_db
      - MYSQL_ROOT_PASSWORD=123123
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql_data:/var/lib/mysql  # -v option