services:
  app:
    image: node-mind:v1
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npx prisma db push && node dist/main.js "
    restart: always
    working_dir: /app
    ports:
      - 3000:3000
    container_name: mind_control_app
    env_file:
      - ./config/.env.prod
