services:
  app:
    image: node-mind:v1
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npx prisma db push && npm run start:prod"
    restart: always
    working_dir: /app
    ports:
      - 3000:3000
    container_name: mind_control_app
    env_file:
      - ./config/.env.prod
    tty: true
    stdin_open: true

