services:
  app:
    image: node:18-alpine
    command: sh -c "rm -rf ./node_modules && npm install && npx prisma db push && npm run start:dev"
    restart: always
    ports:
      - 3000:3000
    working_dir: /app
    container_name: mind_control_app
    volumes:
      - ./:/app
    env_file:
      - ./config/.env.dev

  mongo1:
    image: mongo:6
    hostname: mongo1
    container_name: mongo1
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root!
    env_file:
      - ./config/.env.prod
    ports:
      - '27017:27017'
    volumes:
      - ./mongodb:/data/db
      - ./.mongodb.key:/etc/mongodb.key 
    command:
      - '--replSet'
      - 'rs0'
      - '--keyFile'
      - '/etc/mongodb.key'
