services:
  app:
    image: node:19-alpine
    command: sh -c "rm -rf ./node_modules && rm -rf ./dist && npm install && npx prisma db push && npm run build && npm run start:prod"
    restart: always
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:    # mysql이 server 컨테이너보다 먼저 실행 되게 하는 설정
      - mysqlDB
  mysqlDB:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=MIND_CONTROL
      - MYSQL_CONTAINER_NAME=mysql_db
      - MYSQL_ROOT_PASSWORD=123123
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - db:/var/lib/mysql  # -v option
volumes:
    db: